# Generated by Django 4.2 on 2023-06-23 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='my_model',
            new_name='MyModel',
        ),
        migrations.RenameModel(
            old_name='my_submodel',
            new_name='MySubmodel',
        ),
    ]
